### ISSUE TITLE
Settings not saved?

### ISSUE THREAD

**Issue by juangea** [sorayuki/obs-multi-rtmp#67] opened 2021-02-11 18:49 UTC
When I configure a platform everything works, but as soon as I close OBS, when I reopen it all the configurations are lost.

How can I save my seettings?

Thanks.

**Comment by sorayuki** [comment] 2021-02-16 12:50
try 0.2.5.3
it may be fixed in this version.

**Comment by juangea** [comment] 2021-02-16 14:32
Thanks!

I'll test it and report back :)

**Comment by tormyvancool** [comment] 2021-02-17 15:13
> try 0.2.5.3
> it may be fixed in this version.

I did tried right now: it's **not solved** yet.

**Comment by tormyvancool** [comment] 2021-02-21 14:24
No only: when I deactivate it, it returns activated as soon as I restart OBS.
his plugin, so as it its, should be avoided, till a real stable release is available.

**Comment by jupagose** [comment] 2021-03-01 12:45
If you could, go back to 2.5.0 it works pretty well on OBS 26.1.1

**Comment by sorayuki** [comment] 2021-03-01 12:57
> If you could, go back to 2.5.0 it works pretty well on OBS 26.1.1

Hi, is 0.2.5.1 works there?
I have made a refactor from 0.2.5 to 0.2.5.1. (but it didn't reproduce bug here.)

**Comment by jupagose** [comment] 2021-03-01 13:36
> > If you could, go back to 2.5.0 it works pretty well on OBS 26.1.1
> 
> Hi, is 0.2.5.1 works there?
> I have made a refactor from 0.2.5 to 0.2.5.1. (but it didn't reproduce bug here.)

I'm going to try on 2.5.1

**Comment by sorayuki** [comment] 2021-03-01 14:05
> > > If you could, go back to 2.5.0 it works pretty well on OBS 26.1.1
> > 
> > 
> > Hi, is 0.2.5.1 works there?
> > I have made a refactor from 0.2.5 to 0.2.5.1. (but it didn't reproduce bug here.)
> 
> Do you have a link to 2.5.1 to try it ?

https://github.com/sorayuki/obs-multi-rtmp/releases/tag/0.2.5.1

Here is the link to 0.2.5.1 release.
I want to know when it becomes broken.

**Comment by jupagose** [comment] 2021-03-01 14:40
> > > > If you could, go back to 2.5.0 it works pretty well on OBS 26.1.1
> > > 
> > > 
> > > Hi, is 0.2.5.1 works there?
> > > I have made a refactor from 0.2.5 to 0.2.5.1. (but it didn't reproduce bug here.)
> > 
> > 
> > Do you have a link to 2.5.1 to try it ?
> 
> https://github.com/sorayuki/obs-multi-rtmp/releases/tag/0.2.5.1
> 
> Here is the link to 0.2.5.1 release.
> I want to know when it becomes broken.

I did the tests with version 0.2.5.1 I started two streams, YouTube and Facebook 

Then finished them, closed obs and when I opened it again all right.

The only thing is that I used the configuration created with version 0.2.5.0

**Comment by sorayuki** [comment] 2021-03-01 15:01
> > > > > If you could, go back to 2.5.0 it works pretty well on OBS 26.1.1
> > > > 
> > > > 
> > > > Hi, is 0.2.5.1 works there?
> > > > I have made a refactor from 0.2.5 to 0.2.5.1. (but it didn't reproduce bug here.)
> > > 
> > > 
> > > Do you have a link to 2.5.1 to try it ?
> > 
> > 
> > https://github.com/sorayuki/obs-multi-rtmp/releases/tag/0.2.5.1
> > Here is the link to 0.2.5.1 release.
> > I want to know when it becomes broken.
> 
> I did the tests with version 0.2.5.1 I started two streams, YouTube and Facebook
> 
> Then finished them, closed obs and when I opened it again all right.
> 
> The only thing is that I used the configuration created with version 0.2.5.0, but I changed names and video settings an it remains after obs restart

Thank you for the testing.
Do you have met the issue that configuration lost? If it does, which version is broken there?

**Comment by jupagose** [comment] 2021-03-01 15:06
> > > > > > If you could, go back to 2.5.0 it works pretty well on OBS 26.1.1
> > > > > 
> > > > > 
> > > > > Hi, is 0.2.5.1 works there?
> > > > > I have made a refactor from 0.2.5 to 0.2.5.1. (but it didn't reproduce bug here.)
> > > > 
> > > > 
> > > > Do you have a link to 2.5.1 to try it ?
> > > 
> > > 
> > > https://github.com/sorayuki/obs-multi-rtmp/releases/tag/0.2.5.1
> > > Here is the link to 0.2.5.1 release.
> > > I want to know when it becomes broken.
> > 
> > 
> > I did the tests with version 0.2.5.1 I started two streams, YouTube and Facebook
> > Then finished them, closed obs and when I opened it again all right.
> > The only thing is that I used the configuration created with version 0.2.5.0, but I changed names and video settings an it remains after obs restart
> 
> Thank you for the testing.
> Do you have met the issue that configuration lost? If it does, which version is broken there?

I don't met it, but I was using 2.5.0 since near two months ago without any problems.

**Comment by JamesZerf** [comment] 2021-03-19 03:03
How do I uninstall version 26.1.1 and reinstall version 0.2.5.1? because its only letting me save one output.

**Comment by sorayuki** [comment] 2021-03-19 14:30
> How do I uninstall version 26.1.1 and reinstall version 0.2.5.1? because its only letting me save one output.

If you installed new version with installer, just run installer again then it asks you if you want to uninstall.

If you installed old version with extracting archive, search obs-multi-rtmp in obs folder and delete both dll file and obs-multi-rtmp folder

**Comment by WaveSimm** [comment] 2021-03-23 23:06
I had the same issue.
Here's my solution actually getting from another guy.
I need to stream with this plugin's settings which means you need to use the plugin settings first not just make settings.
Then, it will save the settings.

**Comment by tormyvancool** [comment] 2021-03-24 10:43
I tested right now the 0.2.5.1 as suggested.
W7 and OBS 26.1.1
It doesn't work as it should.
I mean: I setup the positions of the UI's windows, then I do something (also streaming)
But when I close and reopen OBS, the positioning of the windows in the GUI is messed.
And I have to manually re-position them.

**Comment by rhummelmose** [comment] 2021-04-12 18:58
It doesn't work in versions after 2.5.1. The destinations I add are not persisted beyond restart of OBS. I am on the newest OBS 26.1.1.

**Comment by rhummelmose** [comment] 2021-04-12 18:59
Also, the installer does not prompt me to uninstall as it should

**Comment by lovaxi** [comment] 2021-04-13 01:15
唯一可以关闭后保存的就是2.5.0，以后的都不行，关了重开配置就丢了

**Comment by leoleaal** [comment] 2021-04-13 19:37
Same issue in 2.6.0 version. I am on the OBS 26.1.1.

**Comment by sorayuki** [comment] 2021-04-14 01:17
> 唯一可以关闭后保存的就是2.5.0，以后的都不行，关了重开配置就丢了

是0.2.5.1开始不行还是0.2.6.0开始不行？

**Comment by wesslyj** [comment] 2021-04-29 07:38
I have the same issue here

**Comment by mixman68** [comment] 2021-05-15 08:56
i have this issue too, seems to be with very long key of fb, if i put everything else, all is ok

**Comment by eladcandroid** [comment] 2021-06-10 13:33
Same here...

**Comment by ileathan** [comment] 2021-08-06 22:59
This is a duplicate issue, the other issue has the solution which is to first add your rtmp server/key then click modify, then click ok, then it will persist the settings when you close obs.

**Comment by sorayuki** [comment] 2021-09-25 10:47
fixed

**Closed by sorayuki** 2021-09-25 10:47 UTC
